# Task 11 — NumPy Vectorization and Broadcasting

**Objective:** Perform arithmetic operations on complete NumPy arrays, demonstrate broadcasting with compatible shapes, and compare loop-based vs vectorized calculations.

Dataset used: **Iris dataset** (`iris.csv`)


In [1]:
import numpy as np
from pathlib import Path
import time

# Load the 4 numeric columns from the Iris CSV
csv_path = Path("iris.csv")
if not csv_path.exists():
    csv_path = Path("/mnt/data/iris.csv")  # fallback for this environment

X = np.loadtxt(csv_path, delimiter=",", skiprows=1, usecols=(0, 1, 2, 3))

print("Shape of numeric Iris data:", X.shape)
print("\nFirst 5 rows:")
print(X[:5])


Shape of numeric Iris data: (150, 4)

First 5 rows:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


## 1. Vectorized Arithmetic

In [2]:
# Arithmetic on complete arrays — no explicit Python loops
print("Original first 3 rows:\n", X[:3])

print("\nAdd 2:")
print(X[:3] + 2)

print("\nSubtract 1:")
print(X[:3] - 1)

print("\nMultiply by 10:")
print(X[:3] * 10)

print("\nDivide by 2:")
print(X[:3] / 2)

print("\nSquare every value:")
print(X[:3] ** 2)


Original first 3 rows:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

Add 2:
[[7.1 5.5 3.4 2.2]
 [6.9 5.  3.4 2.2]
 [6.7 5.2 3.3 2.2]]

Subtract 1:
[[ 4.1  2.5  0.4 -0.8]
 [ 3.9  2.   0.4 -0.8]
 [ 3.7  2.2  0.3 -0.8]]

Multiply by 10:
[[51. 35. 14.  2.]
 [49. 30. 14.  2.]
 [47. 32. 13.  2.]]

Divide by 2:
[[2.55 1.75 0.7  0.1 ]
 [2.45 1.5  0.7  0.1 ]
 [2.35 1.6  0.65 0.1 ]]

Square every value:
[[26.01 12.25  1.96  0.04]
 [24.01  9.    1.96  0.04]
 [22.09 10.24  1.69  0.04]]


## 2. Broadcasting Examples

In [3]:
# Broadcasting Example 1: scalar + array
# Scalar 1.0 is broadcast to every element of the array.
example1 = X[:3] + 1.0

print("Example 1 — Scalar broadcasting:")
print("X[:3] shape:", X[:3].shape)
print("Result:\n", example1)


Example 1 — Scalar broadcasting:
X[:3] shape: (3, 4)
Result:
 [[6.1 4.5 2.4 1.2]
 [5.9 4.  2.4 1.2]
 [5.7 4.2 2.3 1.2]]


In [4]:
# Broadcasting Example 2: 1D feature vector + 2D array
# Shape (4,) is broadcast across all rows.
feature_adjustment = np.array([0.1, 0.2, 0.3, 0.4])
example2 = X[:3] + feature_adjustment

print("Example 2 — Row/feature-vector broadcasting:")
print("Data shape:", X[:3].shape)
print("Adjustment shape:", feature_adjustment.shape)
print("Result:\n", example2)


Example 2 — Row/feature-vector broadcasting:
Data shape: (3, 4)
Adjustment shape: (4,)
Result:
 [[5.2 3.7 1.7 0.6]
 [5.  3.2 1.7 0.6]
 [4.8 3.4 1.6 0.6]]


In [5]:
# Broadcasting Example 3: column vector with a 2D array
# Each row is divided by its own maximum value.
row_max = X[:5].max(axis=1, keepdims=True)   # shape (5, 1)
example3 = X[:5] / row_max

print("Example 3 — Column-vector broadcasting:")
print("Data shape:", X[:5].shape)
print("row_max shape:", row_max.shape)
print("Result:\n", example3)


Example 3 — Column-vector broadcasting:
Data shape: (5, 4)
row_max shape: (5, 1)
Result:
 [[1.         0.68627451 0.2745098  0.03921569]
 [1.         0.6122449  0.28571429 0.04081633]
 [1.         0.68085106 0.27659574 0.04255319]
 [1.         0.67391304 0.32608696 0.04347826]
 [1.         0.72       0.28       0.04      ]]


## 3. Useful Vectorized Data-Science Operation

In [6]:
# Center each feature by subtracting its column mean.
# Column mean has shape (4,) and is broadcast across all 150 rows.
column_means = X.mean(axis=0)
centered = X - column_means

print("Column means:", column_means)
print("\nFirst 3 centered rows:")
print(centered[:3])


Column means: [5.84333333 3.05733333 3.758      1.19933333]

First 3 centered rows:
[[-0.74333333  0.44266667 -2.358      -0.99933333]
 [-0.94333333 -0.05733333 -2.358      -0.99933333]
 [-1.14333333  0.14266667 -2.458      -0.99933333]]


## 4. Loop-Based vs Vectorized Calculation

In [7]:
# Use a larger repeated array so the speed difference is easy to observe.
big_X = np.tile(X, (1000, 1))

# Loop-based square
start = time.perf_counter()
loop_result = np.empty_like(big_X)

for i in range(big_X.shape[0]):
    for j in range(big_X.shape[1]):
        loop_result[i, j] = big_X[i, j] ** 2

loop_time = time.perf_counter() - start

# Vectorized square
start = time.perf_counter()
vector_result = big_X ** 2
vector_time = time.perf_counter() - start

print(f"Loop time:       {loop_time:.6f} seconds")
print(f"Vectorized time: {vector_time:.6f} seconds")
print(f"Speed-up:        {loop_time / vector_time:.2f}x")
print("Same result:", np.allclose(loop_result, vector_result))


Loop time:       0.472940 seconds
Vectorized time: 0.027864 seconds
Speed-up:        16.97x
Same result: True


## Conclusion

- **Vectorization** performs operations on whole NumPy arrays instead of writing explicit Python loops.
- **Broadcasting** allows NumPy to operate on arrays with compatible shapes.
- Vectorized NumPy code is usually **shorter, cleaner, and much faster** because the heavy computation is performed in optimized compiled code.


## Interview Questions

**1. What is vectorization?**  
Vectorization means applying an operation to an entire NumPy array at once instead of processing elements one by one using Python loops.

**2. What is broadcasting in NumPy?**  
Broadcasting is NumPy's ability to perform arithmetic between arrays of different but compatible shapes by automatically expanding the smaller shape conceptually.

**3. Why is vectorization useful for data science?**  
It improves execution speed, reduces Python code, makes calculations easier to read, and works efficiently with large numerical datasets.
